### ISSUE TITLE
Convert Galfit Parser to work with GalfitM

### ISSUE THREAD

**Issue by ppxkg1** [astronomeralex/galfit-python-parser#6]
Hi Alex,

I wanted to ask if you know of or have a version of this code that works with GalfitM? 

It works perfectly for regular galfit, but i'm struggling to understand how it calculates the number of components, as I was trying to make a few changes to it for some personal use where i'm analysing data from GalfitM, which produces image blocks larger than 4. No matter what I do I keep getting the assert error for the number of components in the header. 

Any help on this would be great!

-- KG

**Comment by astronomeralex** [comment]
Hello! Thanks so much for reaching out! As it turns out, I have been out of the field for over 5 years now, so I can't be of much help, but know you're welcome to play with the code as much as you'd like and submit PRs! You might want to reach out to @sedonaprice, who's also worked on this code. As to the assertion error, try commenting out line 25? This code was originally written for the GalFit version I used years ago so I'm not sure if it breaks on newer versions. Good luck!

**Comment by ppxkg1** [comment]
Thanks for the reply! i'll give your suggestions a go :)
